# Generated by Django 3.2.10 on 2022-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForBiliUsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('user_set', models.TextField(blank=True, null=True)),
                ('music_name', models.CharField(blank=True, max_length=9000, null=True)),
                ('now_music_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('lyric_name', models.TextField(blank=True, null=True)),
                ('who_play', models.IntegerField(blank=True, null=True)),
                ('play', models.IntegerField(blank=True, null=True)),
                ('replay', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'for_bili_users_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForBiliUsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('is_admin', models.IntegerField(blank=True, null=True)),
                ('music_url', models.CharField(blank=True, max_length=30, null=True)),
                ('lyric_url', models.CharField(blank=True, max_length=30, null=True)),
                ('is_running', models.CharField(blank=True, max_length=6, null=True)),
                ('room_id', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'for_bili_users_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('read', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
    ]
