# Generated by Django 3.2.16 on 2023-01-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_forbiliusersdata_forbiliusersinfo_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('room_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('settings', models.TextField(blank=True, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lottery',
                'managed': False,
            },
        ),
    ]
