# Generated by Django 3.2.16 on 2023-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_lottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OBS_Pet',
                'managed': False,
            },
        ),
    ]
